### ISSUE TITLE
G302 (HID++2.0) shows strange resolution options

### ISSUE THREAD

**Issue by phomes** [libratbag/libratbag#106]
The G302 shows:
`ratbag raw: sensor 0: current dpi: 1596 (default: 0) min: 252 max: 4032 steps: 84
ratbag debug: device is at 1596 dpi (variable between 252 and 4032).`

While LGS has 48 steps from 240 - 4000.

Is this common for the mice using HID++2.0? Which range should I use for the hwdb entry?

**Comment by roothorick** [comment]
This is what my G303 says:

    ratbag raw: sensor 0: current dpi: 3200 (default: 800) min: 50 max: 12000 steps: 50
    ratbag debug: device is at 3200 dpi (variable between 50 and 12000).

The high end matches up with the official specs, but this mouse doesn't officially go lower than 200.

This makes me think those numbers are real, and LGS obscures the actual capabilities of the mouse to match up with their official specifications. If the mouse's actual hardware is actually slightly _better_ than the spec, no one will complain even if they do notice, right? ;)

**Comment by bentiss** [comment]
Yeah, these are raw values from the sensor. I don't think Logitech would purposely degrade the specs of the mouse, but I would think that the mouse might not pass quality if you are using out of advertised bounds.

Currently HID++ 2.0 devices don't have a DPI list like HID++ 1.0 do. I am not sure if this is required or if a round up/down to the closest 50 is not enough.

If someone wants to have a deeper look into it, we can keep the bug open, but otherwise I think I'll just close it next time I'll do a pass at libratbags bugs.

**Comment by ogay** [comment]
Sensor used in G302 has native 84 (rounded) dpi steps, open range is 252 up to 4032.
What product FW shows is always true sensor capability, what LGS does is adjusting to next rounded proxy in the GUI, but sensor always works at his native steps.

- We are not changing or processing the raw delta X / Y send by the sensor.

Goal of the rounding in LGS GUI was to keep some consistency across product and sensor generations, and also somehow ease understanding for standard user.

G302 behavior is a sequel from the past, we finally end up having same dpi steps (50) for all recent gaming sensor mice.
Not exposing sensor dpi range below 200 in LGS is an historical choice.

**Comment by phomes** [comment]
There was nothing to fix here. Let's close the issue
