### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by tolga9009** [libratbag/libratbag#111]
Hi,

I'm the project maintainer of sidewinderd (https://github.com/tolga9009/sidewinderd) and watched this project for a while. It looks like we're trying to solve very similar problems and I wanted to ask, if there is interest in adding keyboard support.

Gaming mice and keyboards share alot of code (macros, profiles, LEDs) and this project seems to have everything important included.

Please let me know, whether there is interest, or not.

Cheers,
Tolga

**Comment by whot** [comment]
we don't have any plans for keyboards right now, simply because it's unclear what keyboards should do (or rather how a generic API to configure keyboards should look like). mice is a slightly better-defined problem, we roughly know now what we expect a generic API to look like, what features we'll expose, etc. keyboards are just a pandora's box because they don't quite have that same common denominator.

**Comment by tolga9009** [comment]
I agree, some keyboards have some unique extra features, like display. But most gaming keyboards have macros, profiles in common - every gaming keyboard has a bunch of them.
       
I think the current API (minus resolution / DPI) would be enough to expose basic functionality. Advanced stuff still can be done in additional user space programs or extensions / forks.

But it's okay, if there are no plans to add keyboards. Just wanted to know, thanks!

**Comment by whot** [comment]
I'm closing this for now, will reopen something when we have plans for keyboards. Right now we're struggling to even find enough time for mice...
