### ISSUE TITLE
HP Omen (Rival 300) not recognised

### ISSUE THREAD

**Issue by nyhilium** [libratbag/libratbag#1201]
ratbagd and piper installed. Mouse does not get recognized
Kubuntu 20.04

**Comment by amfern** [comment]
@perigoso It's similar but not quite the same, looking https://github.com/flozz/rivalcfg, it seems like "SteelSeries Rival 300 HP OMEN Edition" has a different product_id. 
That said it seems like the different product_ids are just a variation of the same Rival 300 because looking at rivalcfg code I don't see any special handling for different product_id's it supports, so it's safe to assume libratbag would support HP Omen also with provided .device file

```
[Device]
Name=SteelSeries Rival 300 HP Omen
DeviceMatch=usb:1038:1718
Driver=steelseries

[Driver/steelseries]
DeviceVersion=1
Buttons=6
Leds=2
DpiRange=50:6500@50
MacroLength=1
```

@nyhilium can you drop the above file as somename.device into /usr/share/libratbag/ and restart ratbagd`. Tell us if it worked?

**Comment by perigoso** [comment]
Hm you're right, but surely it's for marketing reasons and the firmware is the same.

I was under the impression the driver for the 300 wasn't behaving well, so the device file might not be enough

**Comment by perigoso** [comment]
as of #1209 the device should now be recognized, the driver still has some issues, but that is being tracked in #804
