### ISSUE TITLE
"Here, picture, picture, picture" error

### ISSUE THREAD

**Issue by alcomposer** [libratbag/libratbag#130]
[Hi,]

I have installed Piper (with Libratbag & Ratbagd) on Arch, but when I run Piper I am unable save device settings onto device (but I can change device settings & I can see the current loaded presets).

I am guessing the "Here, picture, picture, picture" is an error message, but I don't quite know where to trouble shoot from here.

Any help would be most appreciated, really love Libratbag! Great project!

Cheers,
Alex

**Comment by phomes** [comment]
"Here, picture, picture, picture" just means that no one created an image for your specific mouse.

Which mouse do you have?

**Comment by alcomposer** [comment]
Sorry, I should have stated that: Logitech G303

**Comment by phomes** [comment]
Ok. Piper is not as complete as I thought it was. It seems saving is indeed still todo:
https://github.com/libratbag/piper/blob/6d44a84e451a5ae9aa15e519bbc13f4b4a26d1f1/piper/__init__.py#L324

If you are comfortable with the terminal there is the ratbag-command which will save to the mouse.

**Comment by alcomposer** [comment]
Hey, thanks, Piper isn't working on my system correctly, (Mouse is detected but when I edit button values they are all showing up as button 0).

However ratbag-command is working fine. I was able to change resolutions and modes etc.

Cheers,
Alex

**Comment by whot** [comment]
sorry, I barely have time to spend on libratbag these days, I mostly try to get to pull requests in something resembling reasonable time. Piper is almost abandoned right now.

**Comment by alcomposer** [comment]
Hey @whot, hmm, was looking forward to using Piper with my G303, (hence the PR for the SVG).

However ratbag-command is very useful and works well.

Are there plans to create a piper replacement? (or a GUI frontend to ratbag-command?)

**Comment by bentiss** [comment]
Well, Piper is the Future :-)
ratbag-command needs root access, while Piper uses ratbagd, the systemd service which allows to configure the mouse through dbus, without root access. So basically, we need to enhance piper or have a different TUI if you want one. ratbag-command is first and foremost a developer tool that allows us to test the changes, but we don't really want end-users to use it (because of root access and not very friendly interactions).

To give you a rough idea, we are not GUI developers, but we wanted to have a starting point so others could jump in and improve the setting tool. This did not work as we expected, but we are gladly accepting PR on Piper too.

Note: As @whot said, I am too in a state where libratbag is very low priority compared to other projects I have at work. So sorry if you need to wait a bit for answers :(

**Comment by alcomposer** [comment]
No problem at all guys! I was able to do what I want with ratbag-command, change buttons resolution etc.  That's what I wanted to do, and it worked.

I would be happy to help out with more mice SVG's for the GUI (if that helps).

**Comment by bentiss** [comment]
> I would be happy to help out with more mice SVG's for the GUI (if that helps).

That will definitively help :) Any help is appreciated, and this part would be a great addition.

**Comment by alcomposer** [comment]
Ok! I already have the g900 done, (I did this as a top view as that thing has SOOOOO many buttons!).

**Comment by whot** [comment]
afaict, commit e9f0c fixed this one?

The piper issues are still what they are, but @Hjdskes is working on that so it'll go away. Meanwhile, the SVG error should be fixed for this mouse now, so we're good here.
