### ISSUE TITLE
glorious model O showing wrong dpi list again?

### ISSUE THREAD

**Issue by Alib234** [libratbag/libratbag#1535]
Information

    ratbagd version (ratbagd --version): 0.17
    Distribution: Arch
    Kernel version (ex. uname -srmo): Linux 6.5.5-273-tkg-pds x86_64 GNU/Linux

just like in issue #1476
dpi shows from 0 to 2000, while it should show from 0 to 12000 for the model O, not sure how long this has again been broken for

**Comment by staticssleever668** [comment]
Hi! It's probably not *like* that issue again, it *is* the same issue. We haven't had a new release yet, I've only recently pushed through the last blocker, so I hope release soon.
Since you are on Arch, you can use {libratbag,piper}-git from AUR for now, it's what I do myself. :smile: 

By the way, if you by any chance have an account on AUR, could you ask piper-git maintainer to drop the libibus dependency? Piper never actually depended on it.

**Comment by Alib234** [comment]
oh my bad, thought there was maybe a minor version release since april
also doesn't explain how it fixed itself after a ratbag update a few days after u responded to me in that issue
anyways, cheers and sorry for my dumass
