### ISSUE TITLE
Driver support, but also a suggestion

### ISSUE THREAD

**Issue by hfc2x** [libratbag/libratbag#1545]
I was going to ask if support for the EVGA X12 gaming mouse could be added, but I noticed there are other closed issues about other EVGA mice because the feature can't be added due to a lack of driver developers for this brand.

Of course, I don't want to come across like I'm demanding this to be added, but I thought it would be helpful to have a tag for issues on this repository with regards to devices that can't have support added for the same reason (lack of driver developers). I thought instead of closing such issues, it would be more helpful to tag them as "help wanted" or similar, since this could make it easier for a potential developer to find the issues this way and issue the required pull requests.

I think it could also help with other kinds of contributions, like for example if it was possible to have a P.O. box where someone interested may be able to send hardware donations and the like (I for one would be willing to donate such a mouse just for this).

**Comment by staticssleever668** [comment]
>  I thought instead of closing such issues, it would be more helpful to tag them as "help wanted" or similar, since this could make it easier for a potential developer to find the issues this way and issue the required pull requests.

I closed a bunch of such issues recently because they produce a lot of noise in the list of issues, crowding up issues that could actually be worked on. Let's face it - it's pretty rare that somebody contributes a new driver, so instead of keeping a bunch of open issues nobody is probably going to work on, we may as well close them.
Your proposition sounds good, we could look up issues like `is:issue is:open -label:"needs new driver"`, but now that I think of it, if anything, somebody off the internet is more likely to work on one of existing issues rather than writing new features, so I think it's better to have them closed so that that's the way issue tracker looks for everyone without filtering.

> I think it could also help with other kinds of contributions, like for example if it was possible to have a P.O. box where someone interested may be able to send hardware donations and the like (I for one would be willing to donate such a mouse just for this).

That could be nice, but writing new drivers needs a *lot* of motivation, which is the most important thing, and just owning a device doesn't give it.
I myself contributed to drivers for devices I own as it feels personal, but I would not for example switch devices with a friend for some time just to make it compatible with libratbag, it doesn't feel as useful to me.

> I was going to ask if support for the EVGA X12 gaming mouse could be added, but I noticed there are other closed issues about other EVGA mice because the feature can't be added due to a lack of driver developers for this brand.

Yeah, I would've closed the issue in the same way. :)
Really, if anyone decides to write a new driver, they can always make a new issue for that or ask to reopen an existing one.
