### ISSUE TITLE
ROG Gladius 2 in supported list but not detected

### ISSUE THREAD

**Issue by SmoothBrainApe** [libratbag/libratbag#1554]
I have ASUS ROG Gladius 2. I installed 'sudo apt install libratbagd' and restarted. I ran 'ratbagctl list' and says 'No devices available.'

 Is this a bug?

**Comment by staticssleever668** [comment]
Hello! Could it be an older version of libratbag? Gladius II is supported since v0.17 (the latest release at the moment). What's the output of `ratbagd --version` for you?

For example, Ubuntu 22.04 LTS only has v0.16 - the previous release.
If it's `0.17` there could be an issue with libratbag, then please share the output of ratbagd in verbose mode - `sudo systemctl stop ratbagd.service && sudo ratbagd --verbose`.


> 'sudo apt install libratbagd'

Also, I think this is supposed to be `sudo apt install ratbagd`. :smile:

**Comment by SmoothBrainApe** [comment]
It was v0.16. My bad. I installed it from the distro repo. I will try compiling from source. Thanks!

**Comment by staticssleever668** [comment]
Feel free to ask for help if you have any difficulties!
