### ISSUE TITLE
Missing python gobject dependency in meson

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#193]
Trying out a fresh container:
```
root@09dec7f4ad8b libratbag]# ratbagctl list-devices
Traceback (most recent call last):
  File "/usr/bin/ratbagctl", line 29, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

Installing python3-gobject makes ratbagctl happy, but meson should complain about this missing dependency.

**Comment by whot** [comment]
Problem is: meson is a *build* system but this is a run-time issue. Which I guess is a general python issue since we don't need a lot of stuff to actually build it. I'm not sure we should introduce run-time dependencies into meson's build system because that still doesn't guarantee they're available (think: Fedora package)

**Comment by bentiss** [comment]
Fair enough.
We can track build and run-time dependencies in the circle.yml file, and track those per distribution.

Closing this one then.
