### ISSUE TITLE
Setting DPI for the G500s triggers assertion

### ISSUE THREAD

**Issue by Susurrus** [libratbag/libratbag#23]
I have the Logitech G500s and running the `dpi set` command causes an assertion error.

```
$ sudo tools/ratbag-command dpi set 800 /dev/input/event5
ratbag-command: libratbag.c:925: ratbag_resolution_set_dpi: Assertion `profile->device->driver->write_resolution_dpi' failed.
```

**Comment by cvuchener** [comment]
I think this happens because the operation is not implemented.

**Comment by whot** [comment]
indeed, we can't change the hidpp10 resolutions yet, still figuring out how the profile looks exactly in memory

**Comment by cvuchener** [comment]
This reminds me a question I have about resolutions in libratbag. What is "dpi set" supposed to do exactly?
 - Change the resolution for the current mode, in the (current) permanent profile?
 - Switch to a mode with the corresponding resolution?
 - Set the current resolution as a temporary setting?

I guess it is the first one. But the third would be interesting too for changing the resolution while playing one game or for implementing a software "dpi shift" button.

The second one is problematic. The windows software tries to do it when clicking on a mode but it does not work correctly. What it does is just setting the current resolution (with 0x63), and not even bothering setting the LEDs accordingly. The problem is that the commands 0x63 (resolution) and 0x51 (LEDs) temporarily change the settings of the current mode. The settings are still there if you switch to another mode and back (with the +/- buttons), until you restore the settings with 0x63 and 0x51 or reload the profile with 0x0F. I don't think there is way (at least with the G500/G500s) to get/switch the current resolution mode (tell me if I am wrong).

**Comment by whot** [comment]
all the ratbag-command options work on the active profile/resolution/button/etc. unless specified otherwise. so dpi set is "set the dpi for the currently active resolution of the currently active profile".
that's all I ever want it to do tbh, libratbag is about *configuring* the device after all. if there's a need for temporary settings or something more complex like runtime dpi-switching this should be in a separate tool using libratbag to change on the fly. but that logic would be outside the library and the basic commands we provide, stuff like that gets complicated very quickly and it's hard to make it a generic library layer option.

**Comment by cvuchener** [comment]
Okay but then you can remove support for the G5, since there is nothing to do with it (no hardware profile, only temporary settings).

**Comment by whot** [comment]
but that temporary setting is still stored in the hw right? even if it's not persistent across unplugs.
if so, the device would still count has having one profile

**Comment by cvuchener** [comment]
Yes, they are hardware settings. I have just made more test with the G5 (2007/blue&black) and it does not behave the same way than the G500.
 - 0x63 switch the resolution mode (not what I describe above). It works like the +/- buttons have been pressed except that it does not change the LEDs and that you can access a hidden 1600 dpi mode (only 400, 800 and 2000 are accessible from the buttons).
 - 0x51 change the LEDs status but the setting is lost after switching mode with the buttons (the G500 keeps it).
 - the button settings are changed with "Individual features" (0x01), buttons are grouped by pair (+/- and tilt wheel) and have only two settings: default (change resolution or horizontal wheel) or generic buttons. I don't know how that would fit in ratbag profiles.
 - I think the polling rate (0x64) is the same though.

**Comment by whot** [comment]
Regarding 0x63 - give this one a try please: 
https://github.com/whot/libratbag/tree/wip/hidpp10-sensor-resolution
Note the commit message though, this really does change the "current" resolution, it doesn't write it to a profile as I'd like it to long term. It's a hack for testing until we fix the profile handling.
So just to reiterate: what we currently do here isn't what I'd like it to do long-term.

Regarding 0x51: that should be a setting in 0x01, FEATURE_BIT_R2_HOST_SW_CONTROLS_LEDS

Regarding the button settings: that's something we'll have to somehow fix through the "special" button actions. Benjamin and I talked about this a couple of weeks ago, but my jetlagged brain is a bit blurry atm.

**Comment by cvuchener** [comment]
> Regarding 0x51: that should be a setting in 0x01, FEATURE_BIT_R2_HOST_SW_CONTROLS_LEDS

This feature is not available on the mice I tested (G5 and G500). Not all features are supported by every device. See the [features documentation](https://github.com/cvuchener/g500/blob/master/doc/commands/01-features.md).

**Comment by whot** [comment]
ok thanks, I'll double-check this tomorrow and test this here to make sure. this one we have docs for.

**Comment by cvuchener** [comment]
> Regarding 0x63 - give this one a try please:
https://github.com/whot/libratbag/tree/wip/hidpp10-sensor-resolution

It worked the first time. But then my resolution is not in my profile and ratbag-command fails before doing anything.

```
ratbag raw: Fetching current resolution
ratbag raw:   expected_header:		?? 00 81 63
ratbag raw:   expected_error_dev:	10 00 8f 81 63 00 00
ratbag raw: output report: 10 00 81 63 00 00 00
ratbag raw: input report:  10 00 8f 81 63 02 00
ratbag raw:     HID++ error from the device (0): ERR_INVALID_ADDRESS (02)
ratbag raw:   expected_header:		?? 00 83 63
ratbag raw:   expected_error_dev:	10 00 8f 83 63 00 00
ratbag raw: output report: 10 00 83 63 00 00 00
ratbag raw: input report:  11 00 83 63 04 00 04 00 80 02 00 00 8f 00 00 8f 00 00 ff ff
ratbag raw:   received: 11 00 83 63 04 00 04 00 80 02 00 00 8f 00 00 8f 00 00 ff ff
ratbag debug: driver match found: Logitech HID++1.0
Error: Failed to retrieve the active resolution
```
The resolution (0x0004) is read correctly, but I think it fails to match it with an existing mode in my profile.

**Comment by whot** [comment]
sorry, I forgot to mention that. this is expected behaviour and a result of us changing the active resolution only, not the profile-based one. so it'll only work once after plugging in, unless you pick a resolution that's in the profile.

did you test this on the G5 or the G500? it's still using the scheme3 (long report), I was hoping the G5 uses the short report and works (I can't test this here)

**Comment by cvuchener** [comment]
This is the G500. I don't expect the G5 to work because of [this comment](https://github.com/libratbag/libratbag/commit/e87a4d6653bbb104e27fd003bc36015b6e2c445a#commitcomment-13736078).
