### ISSUE TITLE
Non-systemd ratbagd daemon?

### ISSUE THREAD

**Issue by ntzrmtthihu777** [libratbag/libratbag#239]
Gentoo user here. I use openrc init, and was wondering how much of a trouble it would be to de-systemd the ratbagd daemon and make it an opt-dep?

If upstream doesn't want to do the work, would a pr to make that optional (assuming its not horrible and is generally ok) be accepted?

**Comment by whot** [comment]
we don't care about systemd as init system, but we do use libsystemd as dbus library. That's independent of systemd otherwise.

the dbus bits are 90% of what ratbagd does, replacing libsystemd means effectively rewriting ratbagd. Unless you come up with a much better library and implementation than libsystemd's to handle dbus, this is pretty much a no-go, sorry.

**Comment by Polynomial-C** [comment]
Still, bundling your project so close to systemd can be an issue for non-systemd systems.

Picking up the original reporter's question, would you accept a PR if somebody provides a patch to use ratbagd without libsystemd?

**Comment by bentiss** [comment]
I gave a try this morning to actually start ratbagd in the CircleCI container where we can not run systemd for security reasons. And it appears that if we start manually dbus-daemon, ratbagd/ratbagctl are working fine.

So to add up to what Peter said, ratbagd is only tied to libsystemd, which has a dbus API and not tied to systemd the running daemon.

So, a PR that switches ratbagd from libsystemd to anything else would need to provide some true benefits (clarity of code, better API, more concise, etc...).

I don't think we are against such a PR, but we just don't see the benefit of doing such work and possibly degrading the code because some distribution don't ship libsystemd, which is not systemd itself.

**Comment by whot** [comment]
I recommend if you're really adamant about this, start with a patch that adds the Manager and the Device interface and submit it as a WIP for review. That way you're not wasting too much time if it's no good. As @bentiss said, not against changing but it has to be useful and easy-to-maintain code.

**Comment by Polynomial-C** [comment]
Just one followup comment (which I am not intending to annoy you with).
It's a real nightmare to install only parts of systemd without installing the rest of it. systemd upstream did **nothing** to support this. If you want to know how much work it is to just get the udev part of systemd installed, look what the Gentoo people had to do in the [udev ebuild (autotools based)](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/udev/udev-233.ebuild#n137) / [udev ebuild (meson based)](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/udev/udev-234-r1.ebuild#n133). This is one of the main reasons why Gentoo forked eudev from systemd.
I'm sure this post might not convince you to drop libsystemd dependency but I still have hope someone will come up with a patch that you accept for inclusion.
It's really sad that just when I added a [libratbag package](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/libratbag) to Gentoo you added that systemd dependency which leaves me being unable to further maintain this package in Gentoo because I don't use systemd and have no intention to even install the tiniest piece of it.

**Comment by whot** [comment]
as said above, it's not so much a dependency but the central component of ratbagd. swapping it means essentially rewriting the core of ratbagd. Doable, but won't be done by us and unless there's some real technical merit it's a no-go.

**Comment by h1z1** [comment]
Was about to open a bug report having run into this trying on CentOS, I'm quite perplexed by your comment @whot - 

> it's not so much a dependency but the central component of ratbagd.

   That _IS_ a dependency and even on a distro like CentOS which unfortunately uses systemdickhead, it still doesn't compile because the headers you rely on are not in a system path.  They are part of the debuginfo rpm.  Not to mention the current version in 7 is 219 while you require a much newer one (227).

Neat project though, wish it worked standalone.

**Comment by emersion** [comment]
FWIW, [basu](https://github.com/emersion/basu) offers the sd-bus library without the rest of systemd. Although it seems like libratbag also depends on sd-event.

**Comment by TimB87** [comment]
Adding to the last statement, i was able to compile ratbag up until the point where sd-event.h was needed.
