### ISSUE TITLE
USB sniffing

### ISSUE THREAD

**Issue by paller** [libratbag/libratbag#27]
This is _NOT_ an issue.

As there are no other discussion or forum options when it comes to Github, I hope you don't mind me asking questions here?

It has been a while since I last looked at the USB protocol when using a windows driver. Back then I used USBlyzer, very nice interface and easy to use. However, I'm once again limited to the 30 days trial which won't get me to the finish line. What are you using?

**Comment by cvuchener** [comment]
I use USBPcap. It's free software (in both meanings) and generates pcap captures that you can read with Wireshark.

**Comment by bentiss** [comment]
I did not know USBPcap. Thanks for the tip.
Except in some very rare cases, I always uses a Windows VM on a Linux host. I then start wireshark (or usbmon) on the host, re-route the USB device over the Windows VM and start from the captures.

Keeping the bug open, this kind of information should go on the Wiki or in the doc in libratbag.

The only thing we have to do is to warn users that they should not do it if there is a EULA mentioning that they can not reverse engineer the protocol. The one from Razer is formulated in this way which is why @whot and I do not want to touch any Razer device.

**Comment by paller** [comment]
I didn't have much luck with USBPcap and wireshark, sticking to USBlyzer for now.

It is some years since I used usbmon, but as I remember it, it was really difficult to make much sense of the data, as there were no decoding of the protocol. As I'm also running Windows as a VM, it's possible to use wireshark on the host even when forwarding the mouse to the VM?

On the matter of Razer, would you reject any contributions exposing the Razer protocol, and would they in that case have to be signed commits, such that *libratbag* is free of any legal issues?

**Comment by whot** [comment]
tbh, I'm not a lawyer so it's really hard to say for me what would make the code free of legal issues. a clean-room implementation (one person documents, one person implements) would be ok for the code, but the second you start looking at the protocol you're violating the EULA (iirc). The only way around that would be to never install and thus accept the EULA but how would you trigger the various functions then?

**Comment by perigoso** [comment]
https://github.com/libratbag/libratbag/wiki/Adding-a-device#protocol
