### ISSUE TITLE
'Default resolution' is 'switching resolutions'

### ISSUE THREAD

**Issue by kaymio** [libratbag/libratbag#348]
Piper and libratbag are on git master.

After setting the 'resolution switch' option on my G900 via the Logitech Software it appears as 'default resolution' in piper. I can change the button to something else and back to 'default resolution' and it returns to changing resolutions in a cycle from low to high and back to low as should 'resolution switch' do. 
When choosing 'resolution switch' there is no action.

I can confirm that resolution down and up are working and stop to cycle at the lowest and highest resolutions. When doing the same with cycle resolution down/up no action can be observed.

When playing around I encountered a small bug which was resolved with a restart of ratbagd
LANG=C piper
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/piper/ratbagd.py", line 192, in callback_handler
    res = obj.call_finish(result)
GLib.Error: g-io-error-quark: Timeout was reached (24)

The extra buttons were unresponsive till the ratbagd restart.

**Comment by Hjdskes** [comment]
Confirmed on my G403 as well; assigning default resolution to a button and pressing that button performs the switch action instead. I think this is a bug in libratbag (hidpp20), because [ratbagd.py contains the correct value](https://github.com/libratbag/libratbag/blob/master/tools/ratbagd.py#L639) for [`RATBAG_BUTTON_ACTION_SPECIAL_RESOLUTION_DEFAULT`](https://github.com/libratbag/libratbag/blob/692f7f008a81bcc1be50efa9ac86b7bcd30130ed/src/libratbag.h#L1368).

**Comment by bentiss** [comment]
@SonicFrog , could you have a look please (regarding the button assignment part only)?

**Comment by SonicFrog** [comment]
I'll take a look as soon as I can!

**Comment by SonicFrog** [comment]
After a few tests, I haven't been able to find a mouse which works correctly with this. I'll get back with a fix once I've had the time to go over the relevant documentation. Probably next Tuesday or Wednesday
