### ISSUE TITLE
Incorrect Button Detection on Logitech G502

### ISSUE THREAD

**Issue by DreadPirateLynx** [libratbag/libratbag#379]
As far as I can tell, libratbag thinks my G502 only has 11 buttons when it really has 13. Based on the svg file, it looks as though the mouse wheel's scroll up and down are missing

**Comment by cvuchener** [comment]
Mouse wheel up and down are not buttons and they are not reprogrammable.

**Comment by DreadPirateLynx** [comment]
xmodmap begs to differ

**Comment by bentiss** [comment]
And libinput (the new cool kid) tends to disagree with those old legacy tools. The wheel events are pointer axis when others are buttons :)

Just to be clear, libratbag is about configuring the mouse with the capabilities it exports. The mouse tells us the wheel can't be remapped, so libratabg can not remap the wheel up/down events. A software solution *could* work, but the point of being able to configure the mouse on one system, transfer the mouse on an other system and keep the configuration would break in this case.

So if the mouse tells us there are 11 buttons, we can't do much more.

**Comment by DreadPirateLynx** [comment]
I know for a fact that the mouse wheel is programmable with Logitech's software for windows, and that those changes a persistent when moving the mouse over to another system

**Comment by bentiss** [comment]
I just checked on plugging a G502 proteus core (non RGB) on Windows with the latest LGS installed, and the mouse wheel up/down button can not be remapped. Only the left/right buttons of the wheel can. Even in the software mode (not on-board memory mode), we can not remap up/down wheel events.

From what I can see, we are equivalent to LGS in this matter (and this would be weird as we are both relying on the same protocol to fetch the info from the mouse).

**Comment by DreadPirateLynx** [comment]
That's really weird. They must have removed functionality in a recent update; it's been about a year since the last time I used it, but I know I used to be able to do it. Okay, you're off the hook.

**Comment by whot** [comment]
> xmodmap, xev and xbindkeys all beg to differ

ftr, wheel **motion** events are converted in the xorg input driver to button 4, 5, 6 7 events. The only reason for this is that when wheel mice got popular in the 90s, the X protocol didn't have any bits to send the extra axis information to the client. So it was accepted that buttons 4-7 should represent vertical and horizontal wheel motion. And the only reason this works is because it's been around so long is because everyone **agrees** on interpreting buttons 4-7 as scrolling now. This is not part of the protocol, it's simply an agreement. xmodmap etc. are simple tools, they don't even know that buttons 4-7 have a special meaning, they just see buttons.

Oh, and that 4-7 mapping means that the fourth mouse button on a device comes through as button 8. And now anything that deals with buttons in X has a line like `real_button = xbutton > 7 ? xbutton - 4 : xbutton` somewhere in the code to work around the wheel buttons.

**Comment by DreadPirateLynx** [comment]
I'm just sayin': telling me "things are much more advanced now that fewer features are supported" sounds bass-ackwards.

Still waiting to find out where to go to get help with using this software. I can't do anything to bindings other than rearranging my mouse buttons; I thought I was supposed to be able to bind keyboard keys to it.
