### ISSUE TITLE
Redesign of the Wiki

### ISSUE THREAD

**Issue by SebastianPfliegel** [libratbag/libratbag#437]
I redesigned the Wiki and wanted to hear your feedback before committing it to the official repository.

https://github.com/SebastianPfliegel/libratbag/wiki

**Comment by whot** [comment]
looks good, thanks. I just pushed commit b50ffef32733f364e8ee13ae7ea338a47c904b6f to make two errors go away (or rather be replaced with a "meson version" error :). So I think you can skip those two bits now.

As for the Ubuntu bits - I'd rather not have these in there. Make it a separate page for Ubuntu if you must but these things have a tendency to go stale quickly. e.g. on fedora you only need to `yum install` the packages, no need to run `pip3 meson`. And: installing meson as root from pip is not something I'd want just as a casual line in a libratbag tutorial, users will blame us if it screws up their system because we recommended it.

**Comment by SebastianPfliegel** [comment]
Great, I'll make the changes and push it to the upstream later

As for the Ubuntu bits, yeah I'm not really fond of Ubuntu myself. I used a Ubuntu (16.04 LTS) Docker instance and figured out the meson problems as the version provided in the repo's is from the stone age ...
I'll refer to some official meson document on how to install it instead.

What are your plans for https://github.com/libratbag/device-notes ? It's outdated as well, isn't it? Should this stay the place to look for the supported devices and the wiki should link to it?

**Comment by whot** [comment]
the device-notes is separate for legal reasons. the idea was that any notes related to a specific device can be added there, and some other developer can then attempt a clean-room implementation in ratbagd. Which would put us in the clear in most jurisdictions.

This hasn't happened so far though, so it ended up being just list of devices. For the wiki, it'd be best to just link to the device files in the repo because that's the up-to-date information about what libratbag supports.

**Comment by SebastianPfliegel** [comment]
The device files lack some information. They show the potential user if their device is supported, but not if all features are supported or if a firmware upgrade is required for example.

I'd be willing to put some effort into it and keeping it up to date ;)
