### ISSUE TITLE
Wrong resolutions on G402 - HIDPP2.0

### ISSUE THREAD

**Issue by dslul** [libratbag/libratbag#484]
From what I understand, the hipdpp20 driver sets a list of resolutions in steps of 50. This is wrong and should at least be specified in the .device file (as it's done on hidpp10).
The G402, for example, has a range of 240-4000 in steps of 80. Any resolution that is not a multiple of 80 is not native.
I also don't understand why piper gives +2 on resolution steps (I don't know how to check if it's a frontend problem or not).

![image](https://user-images.githubusercontent.com/6121202/41096427-d95050dc-6a54-11e8-933f-a9c8da725715.png)

**Comment by whot** [comment]
Closing this in favour of #471 because I just spent some time trying to figure out what device file the G402 even uses on git master. Since the G402 isn't fully supported yet, let's keep one bug open only for that device.

FTR, you can add `DpiRange` property parsing for hidpp20 if it's needed, that's what the device files are for.

Piper's resolutions rely on the list advertised by libratbag and those are sort-of exponentially sorted, see 94320099b042a8f6e54d73e331b39f68dc8c5602

**Comment by xCuri0** [comment]
@dslul @whot now that this is merged what is the fix for this ? I tried adding DpiRange but it did nothing

**Comment by whot** [comment]
the hidpp20 backend doesn't have the `DpiRange` parsing that the hidpp10 backend needs, so adding the property just means it'll get ignored.  Quick check shows that for hidpp20 this should be handled in `hidpp20drv_read_resolution_dpi_2201()` which prints debug messages, so best run `ratbagctl.devel --vvv` to see all that. If the G402 doesn't handle this correctly then you'll have to add the parsing for that property, but let's see if we can get the device to give us the right info first.

**Comment by dslul** [comment]
From what I discovered, the device (AM010) has a range of native resolutions from 252 to 4032 dpi in increments of 84 (instead of the advertised 240-4000 in steps of 80). When you apply, let's say, 800, the device internally selects 840. So you can save in your profile rounded values and have the mouse always apply native resolutions. This is what the Logitech Gaming Software does.
