### ISSUE TITLE
Zowie EC2-A support

### ISSUE THREAD

**Issue by vanillajonathan** [libratbag/libratbag#525]
Device name: Zowie EC2-A
Kernel name of the device: <none>
USB Device ID: `1af3:0001`

    $ lsusb
    Bus 003 Device 002: ID 1af3:0001

Device file:

```ini
[Device]
Name=Zowie EC2-A
DeviceMatch=usb:1af3:0001
LedTypes=dpi
```

Is this information any useful?
I don't know if it could use any generic driver.

---
```ini
[Device]
Name=Lenovo (no name mouse)
DeviceMatch=usb:17ef:6019
```
---
```ini
[Device]
Name=Microsoft IntelliMouse Explorer 3.0
DeviceMatch=usb:045e:0047
```
---
```ini
[Device]
Name=Microsoft IntelliMouse Explorer 4.0
DeviceMatch=usb:045e:0095
```
---
```ini
[Device]
Name=Microsoft Wireless IntelliMouse Explorer 2.0
DeviceMatch=usb:045e:008c
```
---
```ini
[Device]
Name=Microsoft Trackball Explorer
DeviceMatch=usb:045e:0024
```

**Comment by vanillajonathan** [comment]
### Mice
| Device                                        | USB VID:PID |
| --------------------------------------------- | ----------- |
| Razer Orochi 2011                             |  1532:0013  |
| Razer Abyssus 1800                            |  1532:0020  |
| Razer Mamba 2012 (Wired)                      |  1532:0024  |
| Razer Mamba 2012 (Wireless)                   |  1532:0025  |
| Razer Imperator 2012                          |  1532:002F  |
| Razer Ouroboros 2012                          |  1532:0032  |
| Razer Taipan                                  |  1532:0034  |
| Razer Naga Hex (Red)                          |  1532:0036  |
| Razer Orochi 2013                             |  1532:0039  |
| Razer Naga 2014                               |  1532:0040  |
| Razer Naga Hex                                |  1532:0041  |
| Razer Abyssus 2014                            |  1532:0042  |
| Razer DeathAdder Chroma                       |  1532:0043  |
| Razer Mamba (Wired)                           |  1532:0044  |
| Razer Mamba (Wireless)                        |  1532:0045  |
| Razer Mamba Tournament Edition                |  1532:0046  |
| Razer Orochi (Wired)                          |  1532:0048  |
| Razer Diamondback Chroma                      |  1532:004C  |
| Razer Naga Hex V2                             |  1532:0050  |
| Razer Naga Chroma                             |  1532:0053  |
| Razer Abyssus V2                              |  1532:005B  |
| Razer DeathAdder Elite                        |  1532:005C  |

From https://github.com/openrazer/openrazer

**Comment by whot** [comment]
there is no "generic driver", every device needs to be reverse-engineered. The only exception is Logitech, where multiple devices use the HID++ protocol and can thus be handled with the same driver. More or less, and there are other devices that can re-use a driver, but still, there's no generic driver.

Microsoft mice are completely unsupported, we don't have access to the protocol and no-one has reverse-engineered yet.

Razer - the best option would be to hook up the openrazer driver via a libratbag backend. Last I checked (over a year ago) that wasn't doable because openrazer's design isn't really compatible with how libratbag backends work.

**Comment by vanillajonathan** [comment]
@whot 
Many SteelSeries devices seem to share the same driver too.

Missing though is:

- SteelSeries Kana
- SteelSeries Kinzu v3
- SteelSeries Rival 100
- SteelSeries Rival 300
- SteelSeries Rival 500
- SteelSeries Rival 710
- SteelSeries Sensei MLG
- SteelSeries Sensei Wireless

**Comment by whot** [comment]
iirc the steel series still need per-device fixes, and they would need testing by someone with that device to verify it actually works.

HID is the basic protocol, but all devices use vendor-specific protocols to configure the devices. The transport layer is still HID but you have to know that on this device you have to send 0xab with a value of 3 to enable a profile (random example). And that you only get through reverse-engineering that device. Even the bit mentioned in the blog post above seems to have been abandoned by MS in favour of some vendor specific protocol.

**Comment by whot** [comment]
huh, I clicked save too quickly after copying the first device name from the list. I'm going to close this bug because there's nothing actionable here, we don't have a generic driver that applies to all of these devices. So having the list of VID/PIDs may be handy but it definitely won't make the devices work unless someone sits down and puts the effort in, sorry. Best to file individual bugs for the devices you have **but please don't just file the bugs unless you will work on it**. Otherwise they'll just sit in the issue tracker and add noise.
