### ISSUE TITLE
SVG path naming

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#529]
Right now, the svg files are installed to `/usr/share/libratbag/gnome`. Is there any reason to use such specific naming? I suspect the this is related to piper but I don't see any reason on why we should use this path.

**Comment by whot** [comment]
the last element is the theme name (DBus `GetSvg(theme)` argument). history behind it is that we had some SVGs initially but they were mostly ad-hoc (see `data/default/`) Then we started with Piper and got input from the GNOME designers on how to improve and simplify the SVGs.  That's how the current SVG designs started but they're specifically GNOME themed and may look out of place in other desktop environments.

We don't install the original ones anymore because no-one seems to use them, see commit ff39e676150f5f4b6d89795229ad520fac32c36f. But we should leave the path as-is in case we start adding e.g. a KDE theme. And it's internal data only anyway, especially now with piper switching to use the fd directly.

**Comment by Hjdskes** [comment]
Libratbag has several "themes" for the svgs. "Gnome" is one of them, besides "default". The idea is that the style is very specific to GNOME and would not fit in a KDE application.
