### ISSUE TITLE
Add documentation in the README to install libratbag from the distribution packages

### ISSUE THREAD

**Issue by bentiss** [libratbag/libratbag#538]
Currently our README is rather developer centric, and not user centric.

Looking at bug #535, it is clear that we could show some tips to users that compiling libratbag and piper is not the easy path. Now that major distributions all have a libratbag package, users should probably use it.

It's just some documentation changes, so PR welcome!

**Comment by FFY00** [comment]
BTW, I think we should remove the `--prefix=/usr/` from the meson command. It's really bad practice for a user to do that as it might break the distro packages.

**Comment by whot** [comment]
problem is that even with meson, the default prefix is '/usr/local' which usually results in confusion because it may not be added to the `$PATH`, etc. At least with `/usr` it's IMO a good hint that you're overwriting stuff in the system - and it's written to the right directories.

**Comment by FFY00** [comment]
I think we should add an note explaining it then. I really dislike having an example like this writing to `/usr` as it breaks the distro package, but maybe I am biased because I'm a packager :/ . Most distros add `/usr/local` to the path so it wouldn't affect a lot of users, and for the ones that it does, we would have a note saying that this path needs to be added to the global envvar.

**Comment by whot** [comment]
rightyo, that works for me. want to submit a PR? :)

**Comment by Hjdskes** [comment]
I think this is done now with the current Wiki and README. Feel free to reopen.
