### ISSUE TITLE
Comments on SteelSeries

### ISSUE THREAD

**Issue by HughPH** [libratbag/libratbag#543]
Hey guys

I just got the OLED working for SteelSeries Rival 700, and I've put my shoddy C++ (first I've done in about 15 years) in a repo: https://github.com/HughPH/SteelSeriesControl

I'm going to have to look at the SteelSeries driver in libratrag and see how to get the version - I think Rival 700 might use another version again for LEDs. The Colour Cycles (including Breathe) are sent with a set of up to 16 (I expect) "control points" that describe the ramp (3x signed bytes) to get to the next "control point" and the time (in 10ms increments)

I also notice the commands defined in the libratrag's driver are 1 byte, but I read them as little-endian words (since time is passed as a little-endian word) but happy to be proven wrong.

Finally, in my OLED work, I found that I had to set the wValue to 0x0300 when manipulating the OLED; writing to the hidraw_x_ device just wasn't enough. (Otherwise I'd have done the whole project in C#!)

Cheers

**Comment by whot** [comment]
fwiw, the repo is GPLv3 but libratbag is MIT/X11. So we have to be careful here, copying your code cannot be done by anyone but you (since you can then legally commit it as MIT to libratbag). Everyone else cannot re-implement your code either for copyright reasons (other than maybe taking constants). That's always a bit tricky in a MIT vs GPL project. The other way works fine though, so feel free to look at libratbag :)

**Comment by HughPH** [comment]
Thanks, I doubt you'd want to copy my code wholesale though! It's pretty rough and it really just demonstrates the principle. And we're verging on SCO territory too: it's so basic, even if you did it your own way, some of it could very well look like the same code with a few variables renamed.

**Comment by HughPH** [comment]
I'm also happy to fill in the implementation detail if someone wants to provide an outer class or even a header file. That would be more a question of committing relevant code, rather than the whole sorry lot.
