### ISSUE TITLE
Ratbag profile names must be valid UTF-8

### ISSUE THREAD

**Issue by YoyPa** [libratbag/libratbag#617]
Hello,
This is a summary of: https://github.com/libratbag/piper/issues/300

G700 default profile's names are (at least on mine) Profile n° x (x from 1 to 5 incl.).
The ° is not handled correctly and cause the error even if the profile is disabled (unticked in logitech software).

Here are some output from ```./ratbag-command```, while profile names are:
```
0
1
2
3
its°fault
```
```
# yo @ yo-gs in ~/Documents/git/libratbag/builddir on git:master x [17:25:35] 
$ sudo ./ratbag-command info event7                
/dev/input/event7 - Logitech G700 Laser Mouse
               SVG: logitech-g700.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, switchable-profile, disable-profile, button, button-keys, button-macros
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name : '0'
  Resolutions:
    0: 2500x2500dpi @ 1000Hz (active)
    1: <disabled>
    2: <disabled>
    3: <disabled>
    4: <disabled>
  Button: 0 type left is mapped to 'button 1'
  Button: 1 type middle is mapped to 'button 2'
  Button: 2 type right is mapped to 'button 3'
  Button: 3 type thumb is mapped to UNKNOWN
  Button: 4 type thumb2 is mapped to UNKNOWN
  Button: 5 type thumb3 is mapped to UNKNOWN
  Button: 6 type thumb4 is mapped to UNKNOWN
  Button: 7 type resolution-cycle-up is mapped to 'battery-level'
  Button: 8 type resolution-down is mapped to 'button 4'
  Button: 9 type resolution-up is mapped to 'button 5'
  Button: 10 type profile-cycle-up is mapped to 'profile-cycle-up'
  Button: 11 type wheel-left is mapped to 'wheel-left'
  Button: 12 type wheel-right is mapped to 'wheel-right'
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)

# yo @ yo-gs in ~/Documents/git/libratbag/builddir on git:master x [17:27:29] C:1
$ sudo ./ratbag-command profile 3 name get event7
3

# yo @ yo-gs in ~/Documents/git/libratbag/builddir on git:master x [17:27:35] 
$ sudo ./ratbag-command profile 4 name get event7
Traceback (most recent call last):
  File "./ratbag-command", line 2399, in <module>
    main(sys.argv[1:])
  File "./ratbag-command", line 2393, in main
    f(r, cmd)
  File "./ratbag-command", line 1357, in func_profile_name_get
    print(p.name)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb0' in position 3: surrogates not allowed
```

**Comment by whot** [comment]
ok, I think I figured it out. `ord('°')` is 176. This is not valid ASCII but more importantly, it's not valid UTF8. And that gives us two separate issues which I discovered while trying to reproduce this here with a test device:
- ratbag-command fails because python tries to do some automatic utf-8 decoding which can't be printed
- ratbagd gets quietly disconnected from DBus as soon as it sends this down the wire because DBus requires valid UTF-8. libsystemd which we use here doesn't check strings for valid UTF8 before sending so we don't get an error. And DBus just quietly disconnects us without an error anywhere.

The simplest solution here will be to just drop/replace/ignore all characters > 127 in libratbag and eventually figure out how to convert profile names into unicode within libratbag.

**Comment by YoyPa** [comment]
in ratbag-command this change do the trick of ignoring invalid character:
from
```
def func_profile_name_get(r, args):
    p, d = find_profile(r, args)
    print(p.name)
```
to
```
def func_profile_name_get(r, args):
    p, d = find_profile(r, args)
    string = bytes(p.name, 'utf-8', 'ignore')
    print(string.decode('utf-8'))
```

**Comment by whot** [comment]
Yep, that would do the trick but only for `ratbag-command` which doesn't go over DBus. `ratbagctl` which is the tool we ship won't work because we still get disconnected from DBus. So, our solution needs to be either at the libratbag level or in ratbagd (quick glance shows the latter is a lot easier to implement).

**Comment by whot** [comment]
@YoyPa please give #619 a test, thanks!

**Comment by YoyPa** [comment]
No more issue with https://github.com/libratbag/libratbag/pull/619, thanks :).
