### ISSUE TITLE
Test/Check dependencies shouldn't be hard dependencies

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#655]
Currently we have things like `valgrind` as a hard depedency when they are only used for testing. `valgrind` is specifically significant as its size is well above average compared to most packages. We should disable the affected tests when the dependencies are not present instead of failing the meson setup.

**Comment by whot** [comment]
fwiw, this is an intentional decision to have a predictable build setup. In the past (mostly before meson but that's largely coincidental) we used to enable bits depending on whether packages were available or not. The side-effect of that is that users would build the software and report bugs because well, they built without libfoo and thus the behaviour wasn't the same. Now the general attitude is more: have one specific build type that is the accepted default, anything else must be explicitly changed by the user at configure/meson time.

We have an option to disable tests which will also avoid the valgrind dependencies. But if you're running tests, you should also run them in valgrind to spot any leaks or invalid writes/reads.

**Comment by FFY00** [comment]
I wasn't talking about overall dpendencies, I was talking about check depedencies, the ones used to run tests. I was particularly interested in making `valgrind` optional.
