### ISSUE TITLE
Can't get to work from git on KDE Neon (debian)

### ISSUE THREAD

**Issue by ITCMD** [libratbag/libratbag#795]
After successfully installing it with no errors, running the `piper` command in `builddir` gives the following output:

```
setlucas@SetLucas-Lenovo-Z70-KDE:~/piper/builddir$ ./piper
Traceback (most recent call last):
  File "./piper", line 46, in <module>
    exit_status = Application(1).run(sys.argv)
TypeError: __init__() takes 1 positional argument but 2 were given
setlucas@SetLucas-Lenovo-Z70-KDE:~/piper/builddir$ 
```

I'm using a Logitec G602, which I understand is unsupported, but out of hope for the g602 to be supported soon I'd like to get piper going.

I *was* able to get piper working from `apt-get install.` However if I understand correctly this is outdated and not updated regularly?

**Comment by whot** [comment]
that's a bit confusing usually but: `piper` is the to-be-installed command, `piper.devel` is the one to run from within the builddir. So after building, just run `./builddir/piper.devel`, otherwise it'll try to load the various bits from system paths instead of the git tree.

And that's what's happening here, `Application()` takes 1 arg in the git tree (excluding `self`) but no args in previous piper versions. But you're loading the piper module from `/usr/...` somewhere, hence that error.

And yes, I agree: Python packaging is a terrible mess.
