### ISSUE TITLE
`ratbagd.py` should be installed instead of embedded in `ratbagctl`

### ISSUE THREAD

**Issue by FFY00** [libratbag/libratbag#818]
`ratbagd.py` is used in both libratbag and piper but we currently don't install it on the user's machine. This means that we have two different `ratbagd.py` files in two different repos. This file should be installed on the user's machine and then ratbagctl, piper or other clients can import and use it.

This would have prevented PRs such as #775

**Comment by whot** [comment]
`ratbagd.py` is a shortcut that we took a while ago to avoid having to re-implement things like how to access DBus APIs - mainly because ratbagctl and Piper use the same APIs. We explicitly copied it between the repos because the API was still in flux (and so was everything else).

There was talk about properly separating the two now that Piper is effectively finished but like everything else libratbag there wasn't enough time.

Installing ratbagd.py adds quite a few issues. First, it becomes a first-class API which means we can't change things anymore without breaking it. We have in the past changed ratbagd.py's API (but not the DBus API) and that's fine until the next sync point. Having it a shared module means we force everyone to install the latest piper and ratbagd whenever ratbagd.py changes. Made-up example: if we want to change `Ratbagd.devices` into `Ratbagd.get_devices()`, we can do that right now and it'll all work. We can't do that once it's shared.

#775 is a slightly different problem - that only concerns the DBus API and ratbagd.py doesn't help with that. e.g. if we remove a DBus call ratbagd.py would break too and so would every user, so having a shared module doesn't help at all here. We could start versioning ratbagd but that just adds complexity and python is fairly terrible at this.

And finally: once you have a first-class API, people will use it. And with that comes the need for stability and debugging other code, something I don't want to have to do for what is effectively a cheap dbus binding.

So yeah, it won't be installed because we don't want anyone to use it as a module. Easier to copy and sync where needed.
