### ISSUE TITLE
ratbagctl exits with success (0) when DBus call from ratbagd fails

### ISSUE THREAD

**Issue by woky** [libratbag/libratbag#849]
See https://github.com/libratbag/libratbag/issues/848. When DBus call to change mice DPI fails, ratbagctl exits with success (0), which is confusing for debugging problems and problematic for scripts.

**Comment by whot** [comment]
fairly simple explanation for this one: `ratbagctl` is designed as a one-shot tool so it just goes, sends the dbus message and quits rather than stay around to check for any errors.

This is in part also due to the quirky API we need in ratbagd - we cannot know how long the commit itself will take on the device so the `commit` call itself always succeeds and `ratbagd` will handle the `Resync` signal if it ever happens (only on errors). For `ratbagctl` to do the same it'd have to sit idle and wait for N seconds. Where N is a guessed value because it depends on the device and you may still get the error at N + 1 seconds.

**Comment by FFY00** [comment]
Yes, Logitech gaming devices take quite some time to write to as need write the whole profile.

I don't think there's any solution for this. @whot we should probably close the issue?

**Comment by whot** [comment]
now my memory is back: there's a `--keepalive` option to `ratbagctl`. Not 100% it'll show the error in this case but it'll keep ratbagctl alive after sending `commit()` so it may just.

But yeah, other than that I don't think there's a good solution to this atm.
