### ISSUE TITLE
A bit of pedantry: proposal to change all "G PRO" references to just "PRO"

### ISSUE THREAD

**Issue by Hasshu** [libratbag/libratbag#863]
Properly speaking, it's the `PRO` by `Logitech G`: https://twitter.com/LogitechGesport/status/1195429087201746945

**Comment by FFY00** [comment]
What do you mean? We don't refer to anything as "G Pro", we call it "Logitech G Pro".

https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g-pro-wireless.device
https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g-pro.device

**Comment by Hasshu** [comment]
Indeed. But if "G" is part of the brand name in this case, shouldn't, say, the G502 HERO device file be named `logitech-g-g502-hero.device`? (Which sounds rather cumbersome.)

**Comment by whot** [comment]
don't get me wrong, but --- meh :) 

it still shows up as `Logitech G Pro Wireless` wherever the name is used which matches the double-branding (it is still by logitech after all). and the device files are merely to associate the devices for us puny human developers, they're never exposed anywhere. For all the user cares, they could have an md5sum instead of a proper name and still work.

As a general rule: when a vendor has to correct people on the use of their own branding, it's time for marketing to admit they've stuffed up big time...

**Comment by FFY00** [comment]
I just check my G502 and it doesn't even follow that.

```
Logitech, Inc. G502 Proteus Spectrum Optical Mouse
```

**Comment by Hasshu** [comment]
@whot Fair enough.

> I just check my G502 and it doesn't even follow that.

@FFY00 Hence my initial proposal, which would be `logitech-pro.device` and `logitech-pro-wireless.device`. Again, a bit of pedantry.

**Comment by FFY00** [comment]
I think it's easier to just leave the most common name, otherwise it will confuse people.

**Comment by Hasshu** [comment]
> I think it's easier to just leave the most common name, otherwise it will confuse people.

@FFY00 I see your point.
